# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPPlwls1d <- function(bw, kernel_type, win, xin, yin, xout, npoly = 1L, nder = 0L) {
    .Call('_FDAconcur_CPPlwls1d', PACKAGE = 'FDAconcur', bw, kernel_type, win, xin, yin, xout, npoly, nder)
}

#' Cumulative Trapezoid Rule Numerical Integration
#' 
#' Cumulative Trapezoid Rule Numerical Integration using Rcpp
#' @param X Sorted vector of X values
#' @param Y Vector of Y values.
#' @export 
cumtrapzRcpp <- function(X, Y) {
    .Call('_FDAconcur_cumtrapzRcpp', PACKAGE = 'FDAconcur', X, Y)
}

dropZeroElementsXYWin <- function(win, xin, yin) {
    .Call('_FDAconcur_dropZeroElementsXYWin', PACKAGE = 'FDAconcur', win, xin, yin)
}

interp2lin <- function(xin, yin, zin, xou, you) {
    .Call('_FDAconcur_interp2lin', PACKAGE = 'FDAconcur', xin, yin, zin, xou, you)
}

#' Trapezoid Rule Numerical Integration
#' 
#' Trapezoid Rule Numerical Integration using Rcpp
#' @param X Sorted vector of X values
#' @param Y Vector of Y values.
#' @export
trapzRcpp <- function(X, Y) {
    .Call('_FDAconcur_trapzRcpp', PACKAGE = 'FDAconcur', X, Y)
}

