# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interp2lin <- function(xin, yin, zin, xou, you) {
    .Call('_fdaconcur_interp2lin', PACKAGE = 'fdaconcur', xin, yin, zin, xou, you)
}

